#!/bin/sh
# 自定义首次启动配置

# 设置LuCI中文界面
uci set luci.main.lang='zh_cn'
uci commit luci

# 设置系统参数
uci set system.@system[0].hostname='THDN-PrintServer'
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'
uci commit system

# 配置网络
uci set network.lan.ipaddr='192.168.10.1'
uci set network.lan.netmask='255.255.255.0'
uci commit network

# 配置WiFi
uci set wireless.radio0.disabled='0'
uci set wireless.radio0.country='CN'
uci set wireless.radio0.channel='6'
uci set wireless.default_radio0.ssid='THDN-dayin'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='thdn12345678'
uci commit wireless

# 配置防火墙 - 开放CUPS端口631
uci add firewall rule
uci set firewall.@rule[-1].name='Allow-CUPS'
uci set firewall.@rule[-1].src='lan'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='631'
uci set firewall.@rule[-1].target='ACCEPT'
uci commit firewall

# 启用服务
/etc/init.d/cupsd enable
/etc/init.d/p910nd enable

exit 0
